### ISSUE TITLE
Deal ticket

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#10]
In GitLab by @edd on May 31, 2018, 16:43

To be considered a basic trading interface, we need at least a chart to show the price history for the current market

![IMG_0168](/uploads/481ced47d50bb7447c9b98d473db3764/IMG_0168.jpg)

# Requirements
- See a calculated total for the order I&#39;m making
- The sell button should summarise the order I currently have entered
- The buy button should summarise the order I currently have entered
- A numeric input field for entering the size of the order
- A numeric input field for entering the price for the order
- A &#39;Buy&#39; button to execute an order for the selected market at the current size & price
- A &#39;Sell&#39; button to execute an order for the selected market at the current size & price
- A set of buttons that can be used to prefill a price - either buttons along the lines of &#39;Current market price - 5&#39;, &#39;Current market price - 2.5&#39; OR &#39;100&#39;, &#39;200&#39; that immediately set the price to a value
- A set of buttons that can be used to prefill a size 
- An order summary that can potentially include fees in the future

# Design
![Screen_Shot_2018-05-01_at_15.55.22](/uploads/3b4d51860a5923016bc774650a794118/Screen_Shot_2018-05-01_at_15.55.22.png)
(See Sketch file: https://drive.google.com/open?id=1-9_gaAaXvqeuCu6mZY1PWtufXrRAFKSB)

# Task list
- [x] client!8 Create basic deal ticket component that supports setting a price & size, and buying or selling
- [x] client#51 Create a Deal Ticket Button component that can summarise the current order
- [x] client#50 Update vega.trading to use new API
- [x] Create a button group that can prefill values (price and size)

**Comment by ashleyvega** [comment]
In GitLab by @edd on May 31, 2018, 16:44

changed title from **Dea{-k-} ticket** to **Dea{+l+} ticket**

**Comment by ashleyvega** [comment]
In GitLab by @edd on May 31, 2018, 16:58

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on May 31, 2018, 16:58

marked this issue as related to client#51

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 4, 2018, 16:28

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 29, 2018, 17:18

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 17:49

marked this issue as related to client#56

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 15:51

marked the task **client#51 Create a Deal Ticket Button component that can summarise the current order** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 15:51

marked the task **client#50 Update vega.trading to use new API** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Feb 1, 2019, 09:38

mentioned in merge request client!143

**Comment by ashleyvega** [comment]
In GitLab by @edd on Apr 1, 2019, 12:18

marked the task **Create a button group that can prefill values (price and size)** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Apr 1, 2019, 12:18

closed
