### ISSUE TITLE
Set up new test net

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#11]
In GitLab by @edd on Jun 1, 2018, 09:28

# Goal
- Have a more stable testnet running

# Rationale
- Only Dave can update or restart nodes on the current test net
- We're using Dave's servers, but already have some Digital Ocean nodes ready to go

# Tasks
- [x] trading-core#24 - Set up go package path correctly
- [x] trading-core#25 - Produce a Docker image when `trading-core` is built
- [x] vega-container#1 - Write a `dockerfile` that can plug together vega & tendermint with our test net configuration
- [x] trading-core#27 - Update capistrano to prod new test net
- [x] Update vega.trading to use new testnet
- [x] Update stats.vegaprotocol.io to use new testnet
- [x] Decommission constructiveproof.com test net

# Deferred

- ~~Google cloud logging~~ - #21

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 09:48

marked this issue as related to trading-core#24

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 09:54

marked this issue as related to trading-core#25

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 09:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 09:55

marked this issue as related to trading-core#24

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 09:55

marked this issue as related to trading-core#25

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 09:55

removed the relation with trading-core#25

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 09:55

removed the relation with trading-core#24

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 09:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 09:56

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 10:10

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 10:11

marked this issue as related to client#50

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 10:13

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 1, 2018, 10:13

marked this issue as related to vega-stats#5

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 4, 2018, 14:40

marked the task **trading-core#24 - Set up go package path correctly** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 4, 2018, 14:44

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 16:06

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 16:12

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 16:14

marked the task **trading-core#25 - Produce a Docker image when `trading-core` is built** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 8, 2018, 13:35

marked the task **vega-container#1 - Write a `docker-compose` that can plug together vega-core & tendermint with our test net configuration** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 12, 2018, 11:38

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 12, 2018, 11:52

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 13, 2018, 16:52

marked the task **trading-core#27 - Update capistrano to prod new test net** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 13, 2018, 16:52

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 13, 2018, 16:52

assigned to @futurechimp

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 13, 2018, 16:53

unassigned @eddhannay and @cdm

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 13, 2018, 16:54

@futurechimp vega.trading & stats.vegaprotocol.io both now point at the new DO testnet. I've also submitted trading-core!12 to update the capfile. I think this is over to you to make sure we can just turn off the constructiveproof version

**Comment by ashleyvega** [comment]
In GitLab by @futurechimp on Jun 13, 2018, 17:12

marked the task **Decommission constructiveproof.com test net** as completed

**Comment by ashleyvega** [comment]
In GitLab by @futurechimp on Jun 13, 2018, 17:12

closed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 18, 2018, 10:47

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 18, 2018, 10:47

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 5, 2018, 16:16

marked this issue as related to #58
