### ISSUE TITLE
Tests for matching engine

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#13]
In GitLab by @edd on Jun 5, 2018, 10:46

The matching engine in [trading-core](https://gitlab.com/vega-protocol/trading-core/tree/develop/matching) is great, but the test coverage is lower than we need it to be. This ticket represents the work we need to do to get it covered by enough tests that we're happy that we understand the code and will know when we break it.

# Tasks
- [X] Write unit tests for original matching engine
- [X] Build strategy for refactoring
- [X] Remove concept of OrderEntry
- [X] Remove channels from matching engine - operate in request, response fashion
- [X] Remove lookup table from order book
- [X] Replace linked list with slice and add lookup table on a price level
- [X] Add clear ranges for tree descent
- [X] Add more complex scenarios to orderbook_test.go - integration tests 
    - Multiple orders sitting on both sides of the order book
    - Multiple aggressive orders from both sides crossing testing multiple price levels, applying pro-rata and testing both persistent and non persistent scenarios
    - Successful tests should clear the book entirely
    - Write tests for order validation and orders removal
- [X] Write logs that prints actual state of the order book
- [x] Build new data structure for orderConfirmation including (aggressive order, trades resulted and impacted orders present on the book)
- [ ] Add cancellation channel to dispatch information about cancelled orders
- [ ] TBD - add error handling in case unexpected failures in matching engine take place
- [ ] Benchamark performance of refactored matching engine
- [ ] Ensure matching engine is thread safe by adding a mutex and writing test for concurrent use
- [ ] Ensure unit tests for refactored matching engine are working again
- [ ] Document matching engine

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 10:54

changed title from **Test{-ing for trading-cor-}e** to **Test{+s for matching engin+}e**

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 10:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 10:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 10:57

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 12:43

assigned to @makspachucki

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 12:47

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 12:48

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 12:48

marked the task **Build new data structure for orderConfirmation including (aggressive order, trades resulted and impacted orders present on the book)** as incomplete

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 12:48

marked the task **Build new data structure for orderConfirmation including (aggressive order, trades resulted and impacted orders present on the book)** as completed

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 12:49

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 12:51

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 12:52

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 12:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 13:08

marked this issue as related to trading-core#28

**Comment by ashleyvega** [comment]
In GitLab by @makspachucki on Jul 2, 2018, 13:15

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Jul 2, 2018, 13:18

marked this issue as related to trading-core#1

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 16:53

closed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 16:53

removed the relation with trading-core#28

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 16:53

removed the relation with trading-core#1
