### ISSUE TITLE
Settlement engine

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#14]
In GitLab by @edd on Jun 5, 2018, 10:59

The settlement engine is the part of our code that deals with incoming and outgoing funds. It is currently unwritten, so this task represents us scoping out what the settlement engine is going to look like.

# Scope
- [ ] How we interact with Ethereum
- [ ] The smart contract that handles Ethereum staking
- [ ] Settlement to deal with blockchains other than Ethereum

# Tasks
- [ ] Investigate how our trading-core will interact with the smart contract
- [ ] Create implementation tickets in the appropriate project repository & link them to this ticket

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 11:03

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 12:56

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 13:20

marked this issue as related to #23

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 13:23

marked this issue as related to #8

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 13:23

removed the relation with #8

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 15, 2018, 10:51

marked this issue as related to #28

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Feb 20, 2019, 19:18

closed

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Feb 20, 2019, 19:18

reopened

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Feb 20, 2019, 19:19

Replaced by #81

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Feb 20, 2019, 19:19

closed
