### ISSUE TITLE
Review the wording of 0059-VCBS-016

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1559]
## Issue

During an AC review its is required that we review the wording of [0059-VCBS-016](https://github.com/vegaprotocol/specs/blob/master/protocol/0059-STKG-simple_staking_and_delegating.md#0059-STKG-016).

This AC is slightly out of alignment with the curerent implementation and may be a candidate for breaking into smaller ACs:

### Tasks:

- [ ] review this AC
- [ ] reword and/or break out as required
- [ ] detail the priority of these ACs (high/medium/low risk) for the Alpha Mainnet deployment

**Suggested edit**

> Every 30 seconds (and at the end of an epoch) the associated stake is reconciled against the current nomination to ensure that the total nomination is not exceeding the total association. In case it does we proportionally un-nominate from the validators until the nomination is not exceeding the association. It's worth mentioning that for the current epoch nomination balance we consider the minimum stake that the party had for the duration of the period evaluated (from the beginning of the epoch). Also, for next epoch's nomination balance we consider the current balance of the association. Have one party stake 100 tokens split 70-30 between two validators. With a an epoch of length 5 minutes, at the beginning of the epoch remove 50 tokens off the stake. Within 30 seconds of the confirmation of updated association, verify that the nomination balances for the current epoch and next has been removed with respect to the 70/30 split, such that it is now 35/15 (0059-STKG-016)
