### ISSUE TITLE
Review the 41 ACs marked as COSMICELEVATOR

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1568]
## Issue

As we start to spec and work on the [features for cosmicelevator](https://github.com/orgs/vegaprotocol/projects/108/views/29) we need to review the ACs that we stated would be done AFTER enable trading. 

```[tasklist]
### Tasks
- [ ] Review AC's marked as `COSMICELEVATOR`
- [ ] Mark ACs that are in scope of cosmic with valid AC numbers/formats (NNNN-SPEC-NNN) in the `cosmicelevator` branch
- [ ] Mark ACs that are NOT in scope of cosmic with the AC marker `palazzomistero` (NNNN-PALAZZO-NNN) in the `cosmicelevator` branch
- [ ] Consider if the ACs marked as `palazzomistero` are indeed worth keeping or if we should remove them as ACs
```
> Note: AC format for `palazzomistero` ACs should be `NNNN-PALAZZO-NNN` and I will exclude these from the link checks until we get towards the end of the cosmic milestone.

## ACs to review by spec

```[tasklist]
### 0027-ASSP-asset_proposal.md (removed)
- [ ] 0027-COSMICELEVATOR-025
```

```[tasklist]
### 0031-ETHB-ethereum_bridge_spec.md (removed)
- [ ] 0031-COSMICELEVATOR-009
- [ ] 0031-COSMICELEVATOR-019
- [ ] 0031-COSMICELEVATOR-020
```

```[tasklist]
### 0040-ASSF-asset_framework.md (removed)
- [ ] 0040-COSMICELEVATOR-002
```

```[tasklist]
### 0045-DSRC-data_sourcing.md (implemented)
- [ ] 0045-COSMICELEVATOR-016
```

```[tasklist]
### 0047-DSRF-data_source_filter.md(implemented)
- [ ] 0047-COSMICELEVATOR-004
```

```[tasklist]
### 0048-DSRI-data_source_internal.md(implemented)
- [ ] 0048-COSMICELEVATOR-001
- [ ] 0048-COSMICELEVATOR-002
- [ ] 0048-COSMICELEVATOR-009
- [ ] 0048-COSMICELEVATOR-003
- [ ] 0048-COSMICELEVATOR-004
- [ ] 0048-COSMICELEVATOR-005
- [ ] 0048-COSMICELEVATOR-006
- [ ] 0048-COSMICELEVATOR-007
- [ ] 0048-COSMICELEVATOR-008
```

```[tasklist]
### 0049-TVAL-validate_transaction_preconsensus.md (removed)
- [ ] 0049-COSMICELEVATOR-003
- [ ] 0049-COSMICELEVATOR-004
- [ ] 0049-COSMICELEVATOR-005
```

```[tasklist]
### 0055-TREA-on_chain_treasury.md (testable and marked as implemented)
- [ ] 0055-COSMICELEVATOR-050
- [ ] 0055-COSMICELEVATOR-051
- [ ] 0055-COSMICELEVATOR-060
```

```[tasklist]
### 0055-TREA-on_chain_treasury.md (PLAZZO)
- [ ] 0057-COSMICELEVATOR-TRAN-003
- [ ] 0057-COSMICELEVATOR-TRAN-004
```

```[tasklist]
### 0062-SPAM-spam_protection.md (PLAZZO)
- [ ] 0062-COSMICELEVATOR-001
```

```[tasklist]
### 0069-VCBS-validators_chosen_by_stake.md (removed)
- [ ] 0069-COSMICELEVATOR-002
- [ ] 0069-COSMICELEVATOR-003
- [ ] 0069-COSMICELEVATOR-004
```

```[tasklist]
### 0072-SPPW-spam-protection-PoW.md (testable and marked as implemented)
- [ ] 0072-COSMICELEVATOR-007
- [ ] 0072-COSMICELEVATOR-008
- [ ] 0072-COSMICELEVATOR-009
- [ ] 0072-COSMICELEVATOR-010
- [ ] 0072-COSMICELEVATOR-011
- [ ] 0072-COSMICELEVATOR-012
```

```[tasklist]
### 0075-PLUP-protocol_upgrades.md(033 is critical, 012022 are low priority))
- [ ] 0075-COSMICELEVATOR-012
- [ ] 0075-COSMICELEVATOR-022
```

```[tasklist]
### 0076-DANO-data-node.md(implemented)
- [ ] 0076-COSMICELEVATOR-001
- [ ] 0076-COSMICELEVATOR-XXX
```
