### ISSUE TITLE
Architecture of application

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#16]
In GitLab by @edd on Jun 5, 2018, 11:11

We've talked about having a single Electron application that encompasses `trading-core`, Tendermint and the client UI. Currently the test networking running on constructive proof (see #11) is being accessed by a web UI deployed on vega.trading, rather than running locally. We also almost certainly want native mobile phone and tablet clients that can access the network, but they probably won't be able to run Tendermint & Vega. Or... can they?

# Scope
- [ ] How do we want to serve the private, closed alpha UI to people?
- [ ] How many people connect to one vega node? 
- [ ] How could we build mobile clients?

# Tasks
- [ ] Investigate
- [ ] Create implementation tickets in the appropriate project repository & link them to this ticket

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 11:11

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 11:27

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 11:27

marked this issue as related to #17

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 12:57

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Jul 5, 2018, 16:42

marked this issue as related to trading-core#33

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 17:32

marked this issue as related to trading-core#28

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 17:44

marked this issue as related to trading-core#13

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 10:19

marked this issue as related to #32

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 12, 2019, 14:07

closed
