### ISSUE TITLE
Smart product language

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#18]
In GitLab by @edd on Jun 5, 2018, 11:20

On our roadmap for the end of 2019 is a Smart Product Language allowing people to trade custom products. @barnabee has some more ideas about what this will entail. We need to get a shared understanding of what we expect this to be so we can start drawing up some requirements. 

# Scope
- [ ] What are the requirements for this?
- [ ] What are some example markets that we expect people to build?
- [ ] Do we need a whole DSL? Could we just use Go?

# Tasks
- [ ] Investigate
- [ ] Create implementation tickets in the appropriate project repository & link them to this ticket

**Comment by ashleyvega** [comment]
In GitLab by @barnabee on Jun 5, 2018, 11:34

NB: we are likely to bring this work forward a little, particularly once we close the seed round and have the funds to hire for it and kick off some work in parallel.

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 12:57

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 17, 2019, 17:07

closed

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Nov 13, 2019, 15:44

mentioned in merge request !32
