### ISSUE TITLE
Cosmos investigation

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#19]
In GitLab by @edd on Jun 5, 2018, 11:22

[Cosmos](https://cosmos.network/) is an upcoming 'Internet of Blockchains' based on Tendermint. It's going to allow for interoperability between blockchains! 

# Scope
- [ ] What does Cosmos mean for us? How can we use it?
- [ ] Does Cosmos make a compelling case for staying on Tendermint?

# Tasks
- [ ] Read up on Cosmos
- [ ] Evaluate how Cosmos applies to us
- [ ] Create implementation tickets in the appropriate project repository & link them to this ticket

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 11:25

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 12:57

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 13:35

marked this issue as related to #24

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 15:14

marked this issue as related to #23

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 10:41

removed milestone

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 12, 2019, 13:32

closed
