### ISSUE TITLE
Application packaging

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#20]
In GitLab by @edd on Jun 5, 2018, 11:34

Related to #16 & #17 & - how do we want people to install Vega? Depending on the architecture defined in #16, this may mean installing one Vega node on a server for a whole company to access, or it might mean each trader installing an Electron app that is a Vega node.

# Scope 
- [ ] Who is going to be installing this? Server admins or end users?
- [ ] What are our options? Electron? Docker? Flatpak? App store? Vega as a Service? apt? Pacman?

# Tasks
- [ ] Investigate
- [ ] Create implementation tickets in the appropriate project repository & link them to this ticket

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 12:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 12, 2019, 13:32

closed
