### ISSUE TITLE
Monitoring / logging

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#21]
In GitLab by @edd on Jun 5, 2018, 12:48

Logging. We know we'll want to know what's happening with the network, but not exactly what we'll want to know. At the very least, we need to know that the network is alive and making trades. More detailed information on the count & location of nodes, currently deployed versions, throughput and such would all be great. 

# Scope
- [ ] What do we want to monitor on the network? Network health? Trades / orders? Everything?
- [ ] Where do we want to log to? Does anyone have a proposed logging platform? Should we go all ELK?
- [ ] How do we want to log client stuff? Errors only?
- [ ] Is logging opt-in or opt-out?
- [ ] GDPR?
- [ ] will we need to be able to trace money from staking to payout?

# Tasks
- [ ] Update this ticket with information about what we can log about the state of the network
- [ ] Set up a logging endpoint of some sort
- [ ] Create implementation tickets in the appropriate project repository & link them to this ticket

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 12:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 12:58

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 9, 2018, 11:25

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 17:43

marked this issue as related to trading-core#1

**Comment by ashleyvega** [comment]
In GitLab by @edd on Nov 26, 2018, 12:30

assigned to @ashleyvega

**Comment by ashleyvega** [comment]
In GitLab by @ashleyvega on Jan 16, 2019, 15:56

We want to know:
* precise timestamp
* error message (fixed string)
* key-value pairs giving detail
* error origin (a short vague description, e.g. data-store, matching-engine)

and in debug mode
* error origin:
  * source file
  * line number
  * fn/method name
* stack trace

We want:
* colourful logs to stdout/stderr (if they are TTYs)
* logs with a one-line json obj ??

**Comment by ashleyvega** [comment]
In GitLab by @ashleyvega on Jan 16, 2019, 15:57

Extra features:
* different parts of the app should have separate log levels.

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 29, 2019, 14:07

closed
