### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#22]
In GitLab by @edd on Jun 5, 2018, 13:09

We need to make Vega accessible, both in terms of people new to the project getting a node up and running, to people being able to integrate with the APIs. Enough of our existing tech stack makes it easy for us to generate documentation, but we're not currently doing so. We should.

# Scope 
- [ ] Where should we write up 'Getting Started' documentation?
- [ ] Vega node RPC documentation
- [ ] GraphQL documentation?
- [ ] Swagger documentation?
- [ ] Protobuff documentation?
- [ ] Where do we want to deploy documentation - Netlify? 
- [ ] Should we be writing changelogs in the repos?

# Tasks
- [ ] Set up one or more hosting-type situations for documentation
- [ ] Set up a subdomain like docs.vegaprotocol.io
- [ ] Ensure documentation is updated on build/version releases
- [ ] Add tasks to the appropriate projects to generate publishable documentation

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 13:15

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 17:31

marked this issue as related to trading-core#20

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 31, 2019, 16:13

Slate seems like a good choice for a general documentation site: https://github.com/lord/slate (sample: http://lord.github.io/slate)

Extra thing: GraphQL documentation generator: https://github.com/GraphiDocsOrg/docs

**Comment by ashleyvega** [comment]
In GitLab by @edd on Apr 1, 2019, 12:49

Replaced by #98

**Comment by ashleyvega** [comment]
In GitLab by @edd on Apr 1, 2019, 12:49

closed
