### ISSUE TITLE
[Feature]: Improvements to games

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/specs#2233]
# Feature Overview

**In order to** improve the current games functionality
**We will** look into these hopefully "quick fixes"
**So that** people find the games more engaging

## Tasks

Below is a list of suggested improvements based on a few week's experience and feedback we've had from users. 

Suggest we review all of these and decide which to take forward if any.

- [ ] Add a `runningVolumeRequirement` so that in addition to the notional requirement reward creators can ensure that in order to qualify for a reward users must be actively trading and not just sitting on positions
- [ ] Add a `realizedPnL` reward type; this is an alternative approach to the above in terms of forcing active trading rather than sitting on positions
- [ ] Adjust the `relativeReturn` reward type (or create a new fork of it) so that instead of disregarding any key with a loss we rank ALL eligible keys in terms of P&L and reward them.  This would allow the game to account for the situation where the market turns and everyone is losing, but some are losing "better" than others.
  - [ ] For a pro rata game this would mean rewarding all eligible keys some amount
  - [ ] For a ranked game this would mean that keys in loss can still be in the ranking table
- [ ] Other?

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.
