### ISSUE TITLE
Proof of Stake

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#23]
In GitLab by @edd on Jun 5, 2018, 13:19

To quote @barnabee: "...how the S in PoS might work on Vega". This is important for the Settlement Engine (#14)

# Scope
- [ ] Will stake will be in Vega tokens
- [ ] Who might run staking (validator?) nodes
- [ ] How rewards might work.

# Tasks
- [ ] Investigate what Tendermint provides us with
- [ ] Create tickets in the appropriate project repository and link them in this ticket.

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 13:20

marked this issue as related to #14

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 13:21

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 13:23

marked this issue as related to #7

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 15:14

marked this issue as related to #19

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 12, 2019, 13:32

closed
