### ISSUE TITLE
Sharding

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#24]
In GitLab by @edd on Jun 5, 2018, 13:34

One solution to increase throughput and speed is to shard the market, so that nodes have to deal with less traffic. We've talked about sharding by market, or by products, but what's the right way to split it? As Tendermint doesn't natively support sharding, we're effectively setting up a new Tendermint blockchain for each product, is that smart?

# Scope
- [ ] What are the different ways we could slice up all of the traffic?
- [ ] How do we implement sharding?
- [ ] Is sharding required for the private closed alpha?

# Tasks
- [ ] Investigate sharding
- [ ] Agree on an approach to sharding
- [ ] Create tickets in the appropriate projects and link to them from this ticket

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 13:35

marked this issue as related to #19

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 12, 2019, 13:32

closed
