### ISSUE TITLE
Trade history

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#27]
In GitLab by @edd on Jun 5, 2018, 15:26

In the current prototype, the Recent Trades panel only shows trades that happen after the application is opened. We need to show recent trades when the user switches to a new market, and keep updating that list.

# Tasks
- [x] Add read stores to `trading-core`
- [x] Add trades API to `trading-core`
- [x] client#52 - Update client to use trades API
- [x] client#54 - Add filtering & sorting to trades list

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 15:37

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 15:39

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 5, 2018, 15:43

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 2, 2018, 14:52

assigned to @eddhannay and @cdm

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 2, 2018, 14:52

marked this issue as related to client#52

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 2, 2018, 14:52

marked this issue as related to client#54

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Jul 3, 2018, 19:09

marked this issue as related to trading-core#4

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Jul 4, 2018, 12:20

marked the task **Add read stores to `trading-core`** as completed

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Jul 4, 2018, 12:20

marked the task **Add trades API to `trading-core`** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 17:47

marked this issue as related to client#56

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Jul 9, 2018, 17:18

marked this issue as related to trading-core#38

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:33

closed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:33

marked the task **client#52 - Update client to use trades API** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:33

marked the task **client#54 - Add filtering & sorting to trades list** as completed
