### ISSUE TITLE
API infrastructure

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#32]
In GitLab by @edd on Jul 6, 2018, 10:19

We've had a basic API infrastructure in place for a while, but now that we have answered some of the questions in product#16 we know that we will have some APIs in `trading-core` (GRPC, REST) and then another separate project to serve graphql for `trading-ui`.

# Tasks
- [x] Create `vega-graphql` gitlab project
- [x] trading-core#34 Generate REST & grpc APIs from protobuffer definitionsj
- [ ] vega-graphql#1 Create grpc based graphql server

# Post-beta
- [x] trading-core#37 Add FIX support

# Possibilities
- [x] trading-core#35 Add protobuff-over-quic support

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 10:19

marked this issue as related to #16

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 10:24

marked this issue as related to trading-core#34

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 10:26

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 10:31

assigned to @dmgarland and @eddhannay

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 10:37

assigned to @makspachucki

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 11:17

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 11:19

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 11:22

marked this issue as related to trading-core#35

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 12:01

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 12:04

marked this issue as related to trading-core#37

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 12:05

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 9, 2018, 12:15

marked this issue as related to client#57

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Jul 11, 2018, 11:12

marked this issue as related to trading-core#40

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 11, 2018, 11:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 11, 2018, 11:55

marked this issue as related to vega-graphql#1

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:35

marked the task **trading-core#34 Generate REST & grpc APIs from protobuffer definitionsj** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:35

marked the task **trading-core#35 Add protobuff-over-quic support** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:35

marked the task **trading-core#37 Add FIX support** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:35

unassigned @dmgarland

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:35

closed
