### ISSUE TITLE
Establish (and maybe improve) demo tx/s with bots

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#51]
In GitLab by @edd on Sep 24, 2018, 16:46

```
As a Vega employee
I want to know what our transaction/second limit is
So that we can start planning based on that number
```

# Acceptance criteria
- We understand the performance characteristics of our system

# Tasks
- [x] Make all bot orders GTT by default
- [x] Host Maks' bot so that anyone can manually tweak the number of current tx/s
- [x] Add command line switch to automatically delete expired orders

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 16:46

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 16:51

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 17:28

changed title from **{-Live demo-}** to **{+Establish (and maybe improve) demo tx/s stable elevel+}**

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 17:28

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 17:33

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 17:56

marked this issue as related to trading-core#66

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 17:56

marked this issue as related to trading-core#67

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 18:08

changed title from **Establish (and maybe improve) demo tx/s{- stable elevel-}** to **Establish (and maybe improve) demo tx/s**

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 18:09

assigned to @cdm, @makspachucki, and @eddhannay

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 24, 2018, 18:24

unassigned @eddhannay, @cdm, and @makspachucki

**Comment by ashleyvega** [comment]
In GitLab by @edd on Sep 28, 2018, 16:10

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 1, 2018, 14:40

changed title from **Establish (and maybe improve) demo tx/s** to **Establish (and maybe improve) demo tx/s{+ with bots+}**

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 1, 2018, 14:52

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 1, 2018, 15:35

closed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 4, 2018, 15:54

marked the task **Host Maks' bot so that anyone can manually tweak the number of current tx/s** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 4, 2018, 15:54

marked the task **Make all bot orders GTT by default** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 4, 2018, 15:54

marked the task **Add command line switch to automatically delete expired orders** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 7, 2019, 16:12

marked this issue as related to trading-core#320

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 7, 2019, 16:12

removed the relation with trading-core#320
