### ISSUE TITLE
Bot tweaks: Make the charts more realistic

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#57]
In GitLab by @edd on Oct 1, 2018, 14:55

# Current state
![Screenshot_2018-10-01_at_14.55.47](/uploads/88fb391b824824f940431a61a539c668/Screenshot_2018-10-01_at_14.55.47.png)

# Tasks
- [ ] Randomise the upper and lower limits of the order prices so that the top and bottom of the candlestick are less consistent
- [ ] Maybe randomise the time all the bids are executed at so there's some variation
- [ ] @makspachucki to walk @cdm & @eddhannay through starting up the bot with his script, and the API

Related task: product#56

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 1, 2018, 14:58

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 1, 2018, 15:00

marked this issue as related to go-trade-bot#4

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 1, 2018, 15:01

marked this issue as related to go-trade-bot#5

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 1, 2018, 15:03

marked this issue as related to go-trade-bot#6

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 1, 2018, 15:45

assigned to @makspachucki

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 15, 2018, 17:23

closed
