### ISSUE TITLE
Add Matt's public key to servers

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#60]
In GitLab by @edd on Oct 9, 2018, 12:07

@mattrussell36 Please comment with your public key (```cat ~/.ssh/id_rsa.id | pbcopy```) and we'll get it added to all the machines it needs to be on.

Also, add Edd's blink key
# Tasks
- [x] Add keys to devnet
- [x] Add keys to testnet
- [x] Add keys to bot machine
- [x] Add keys to ops

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 9, 2018, 12:09

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 9, 2018, 12:12

```ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCy8ZU99xwodv/wu3xXEsrN3hsGMDd0Qp9SVuKqU0HKnQ9aAzyqv5otX/W2cRlAmrfjcBEAReLYvDZSegCK4WrI/IAVDIjS9UW+E7IA9dw0D6oPBK/tPI311VCmNnX7xSVR/90ad0yFJz+2ZHadK5YSpA6+DmVIFQckwhPqYDuqZ/pGX0pihug0VqHWPgH0wzpjQpSKDJtlk3A4TdAiNDu64KKxyUKytj2bRQFrNY5Fiqcn/VJOZpp+uIRVwhmhX+a0aA77BDqHF8563sWu0UAObA2SIzGC1hHs0M4Z1DzIrpK0DoP5H+Qc2X0mKLF9Wnl2SD4vMEOeW2lpQNk9VSzmzpkXf37Lv9NMtbehYugPtTeCFgfuDNjoUuy6o6JTnYCFAxXe8LPIr6a3iTkxoyBNiKofW9q28SkL5LyO85FgkT3hw9e5FaTDen7A6VaVcFgwCdiDaiPDfZ1msDeBm8tlGqXnVq7dQ5wO5kUEqnzgwN1SUnBwKVUjgU6lr5FthIPQ50q/KVqdgrUJBkn+brr0uJ0oWkPafdv6mkgRdwbEHReKBV3UgXpKeucfG5hqGgSEgLklvbinMpKCEtZQqa6h2bC0YGWPpa35KYTIrGHdf4QJ6uc26wLGf49t/GNSacVF2Nay4s9pMk6awY0TezvFLbMUsNxKByurZfHrc5KMUQ== edd@blink```

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 9, 2018, 12:15

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @mattrussell36 on Oct 9, 2018, 14:17

`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+z6dHiWvAhPGOyceQm/bPkRELKUk1Jc8UXCCfymOtaDm+Ox9b1VLtgFhQ/8ZNc1uzR1EGMMwLBWIUDWusYfy64w+AbaCWjMjupzxDYazvWaQz3nJjan0yckH3oZFfAVoWzk1y20iMJagXcK4aDmcueKrLAEdhq5DhchuSxxKWLV1CQqeQbolUwK4YeYa2NHhIbqs2QayrjJdyIFNpVYUJ1VBnVb/ydf1EFQTd7Ym26+M6EFFlA9SNs7gGJzsNTrn1sA7A/cl4qvK+bAMKM6POIifJ2xrMmtarQXvtQ+9QGVCL1cGOPiBn2Ed7T4jMM6MWdezQZnQ7CuAt6Loj1eieJ7oNZ7hrsSyHuKX2SJyTQaPngWEB/Ed6X3UIgnDMTaOk89N81vug3pPMMnoyLDiVb71ztUfL/VBjhNUtcPVkbX+LDsf0oQ0bcYfYZfmtiMilQXL99Hzrk1ZegxFje88FRCpinMRvMElJ8ejxHS3uhpQ2LMPEg/yCvh/VcryexinhKShK1PEp1bVb/yTNd0rNuol2oIH0p6Xqsgt/ZpUBVa6zExhyUDfXB5UW+xJD0nAj2Mxr6pPM/MXoxBtIy5TZeY1o4Cbj8E/YebRSC5WnBGL9BDTbVqAnl6tAmKMqwKxH2ihN9zPaF3nlR888uJ9mPwj11NvPDu9LJqtu8+fzcw== mattrussell36@gmail.com`

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 16, 2018, 10:41

marked the task **Add keys to devnet** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 16, 2018, 10:41

marked the task **Add keys to testnet** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 16, 2018, 10:41

marked the task **Add keys to bot machine** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 16, 2018, 10:41

marked the task **Add keys to ops** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 16, 2018, 10:41

closed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 17, 2018, 10:37

reopened

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 17, 2018, 10:52

closed
