### ISSUE TITLE
Add order to order list immediately

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#63]
In GitLab by @edd on Oct 15, 2018, 17:52

```
As an impatient trader used to centralised exchanges
In order to know that I placed my order, even before the server has confirmed it
I want the pending order to appear in my orders view
```

Currently when an order is placed, we wait for it to come back as an event from the server before we render it in the client's Order list. This doesn't have to be the case - we know almost everything about the order already, so let's just render it straight away. This is the first instance we have of informing the users about the decentralised nature of Vega and the delay in finality, so let's use it as a testing ground for updating the UI pre-emptively, letting users know how the world SHOULD be, and how we confirm or change that if things change.

# Tasks
- [x] UX workshop around finality confirmation
- [x] Preemptively add the order to the order list in Apollo with a new status of unconfirmed
- [x] Add UI indicator of finality
- [x] Add failure notifications

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 15, 2018, 17:53

made the issue visible to everyone

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 15, 2018, 17:53

marked this issue as related to client#96

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 15, 2018, 17:56

marked this issue as related to client#101

**Comment by ashleyvega** [comment]
In GitLab by @edd on Oct 15, 2018, 17:58

marked this issue as related to client#102

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 31, 2019, 11:39

marked the task **UX workshop around finality confirmation** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 31, 2019, 11:39

marked the task **Add failure notifications** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 31, 2019, 11:39

marked the task **Add UI indicator of finality** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 31, 2019, 11:39

marked the task **Preemptively add the order to the order list in Apollo with a new status of unconfirmed** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 31, 2019, 11:39

closed
