### ISSUE TITLE
Price history charts in the trading interface

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#9]
In GitLab by @edd on May 31, 2018, 13:03

To be considered a basic trading interface, we need at least a chart to show the price history for the current market

# Requirements

# Task list
- [x] client#44 - Create basic chart component with candlesticks & volume graph
- [x] trading-core#34
- [x] trading-core#6 - Create price history API
- [x] client#12 - Remove random data from client UI, use real price history API

# Charts from other exchanges
![Screen_Shot_2018-05-11_at_11.50.56](/uploads/5bf54b765436f282f8354344cc61c08c/Screen_Shot_2018-05-11_at_11.50.56.png)

![Screen_Shot_2018-05-11_at_11.50.44](/uploads/45c821a6ee92d1b93fa55269f1bb3778/Screen_Shot_2018-05-11_at_11.50.44.png)

![Screen_Shot_2018-05-11_at_11.51.35](/uploads/b1433502eba111c6d869ed5cb445fcaa/Screen_Shot_2018-05-11_at_11.51.35.png)

![Screen_Shot_2018-05-11_at_11.52.00](/uploads/344708f7a9b03182c8b3ffc59c8c7870/Screen_Shot_2018-05-11_at_11.52.00.png)

![Screen_Shot_2018-05-11_at_11.52.45](/uploads/2a19957785d46b1831815d372bf74541/Screen_Shot_2018-05-11_at_11.52.45.png)

**Comment by ashleyvega** [comment]
In GitLab by @edd on May 31, 2018, 13:04

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on May 31, 2018, 13:05

marked this issue as related to client#44

**Comment by ashleyvega** [comment]
In GitLab by @edd on May 31, 2018, 13:06

marked this issue as related to client#12

**Comment by ashleyvega** [comment]
In GitLab by @edd on May 31, 2018, 13:06

marked this issue as related to client#6

**Comment by ashleyvega** [comment]
In GitLab by @edd on May 31, 2018, 13:06

removed the relation with client#6

**Comment by ashleyvega** [comment]
In GitLab by @edd on May 31, 2018, 13:06

marked this issue as related to trading-core#12

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jun 20, 2018, 16:59

marked the task **client#44 - Create basic chart component with candlesticks & volume graph** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 17:35

marked this issue as related to trading-core#6

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 5, 2018, 17:48

marked this issue as related to client#56

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 10:29

marked this issue as related to trading-core#34

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jul 6, 2018, 10:29

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:34

marked the task **trading-core#34** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:34

marked the task **trading-core#6 - Create price history API** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:34

marked the task **trading-core#6 - Create price history API** as incomplete

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:34

marked the task **client#12 - Remove random data from client UI, use real price history API** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:34

marked the task **trading-core#6 - Create price history API** as completed

**Comment by ashleyvega** [comment]
In GitLab by @edd on Aug 17, 2018, 11:34

closed
