### ISSUE TITLE
0050-EPOCH potentially has duplicate criteria

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#950]
There are Acceptance Criteria that test delegation. @ze97286 believes it's probably better covered elsewhere, by delegation criteria.

# Tasks
- [ ] Verify that delegation ACs are duplicate, and if so
  - [ ] Remove AC codes from the EPOCH spec and reference the Delegation ones
- [ ] If not, make the distinction clearer

For clarity: I wrote the criteria, @ze97286 wrote the feature. They're not covered by tests, so this is mostly admin.

**Comment by gordsport** [comment]
Close as wont do
